apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kaytu-octopus.yaml
  - sealed-secret-controller.yaml
  - prometheus-operator.yaml
  - cert-manager.yaml
  - loki-operator.yaml
  - postgres-operator.yaml
  - contour.yaml
  - keda.yaml
  - nats.yaml
  - opensearch.yaml
  - vault.yaml
